name: digital_order_system
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  device_preview: ^1.1.0

  # Visual Elements
  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2
  shimmer_animation: ^2.1.0+1

  # Firebase
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.0

  # State Management
  provider: ^6.0.5

  # Format
  intl: ^0.17.0

  # Storage Operation
  get_storage: ^2.1.1

  # Localizations
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf