name: digital_order_system
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Visual Elements
  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2
  adaptive_action_sheet: ^2.0.2
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.2.3

  # Firebase
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.0

  # Core
  provider: ^6.0.5
  intl: ^0.17.0
  get_storage: ^2.1.1
  equatable: ^2.0.5
  package_info_plus: ^3.1.2
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+5
  http: ^0.13.6
  path_provider: ^2.0.15
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  build_runner: ^2.3.3

  # AI and Data analysis
  tflite: ^1.1.2
  csv: ^5.0.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/ai/
    - assets/dataset/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf